# Generated by Django 4.1.5 on 2023-03-02 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menzaDatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menzaDatabase.diner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
